canonical: http://fhir.ch/ig/ch-lab-order
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: ch.fhir.ig.ch-lab-order
name: CH_LAB_ORDER
status: active
version: 0.1.0
dependencies:
  ch.fhir.ig.ch-orf:
    version: 0.10.0
    uri: http://fhir.ch/ig/ch-orf/ImplementationGuide/ch.fhir.ig.ch-orf
    id: chorf
  ch.fhir.ig.ch-core: 2.0.0
