@startuml 4-sepsis-reflex-testing
skinparam rectangle<<resource>> {
  roundCorner 12
  BackgroundColor Blue
  BorderColor Black
  ArrowColor Black
  FontName Arial
  FontSize 16
  FontStyle Bold
}

rectangle "[[ ServiceRequest-4-sepsis-ServiceRequestGrowth-aerobic.html 4-sepsis ServiceRequest Growth ]] " as SRG <<$bProcess>><<resource>> #LightYellow
rectangle "[[ DiagnosticReport-4-sepsis-DiagnosticReport.html 4-sepsis DiagnosticReport Growth ]]" as DRG <<$bProcess>><<resource>> #LightSkyBlue
rectangle "[[ Observation-4-sepsis-ObservationMicrobiolGrowthAerobic.html 4-sepsis Observation\nMicrobiological Growth Aerobic: POS ]]" as OMA <<$bProcess>><<resource>> #APPLICATION
rectangle "[[ Observation-ObservationMicrobiolGrowthAnaerobic.html 4-sepsis Observation\nMicrobiological Growth Anaerobic: NEG ]]" as OMANA <<$bProcess>><<resource>> #APPLICATION
rectangle "[[ Observation-observationMALDI-TOF-Ecoli.html 4-sepsis Observation\nMALDI-TOF: E. coli ]]" as OMTE <<$bProcess>><<resource>> #APPLICATION
rectangle "[[ Observation-observationMALDI-TOF-Kpneu.html 4-sepsis Observation\nMALDI-TOF: K. pneuomoniae]]" as OMTK <<$bProcess>><<resource>> #APPLICATION
rectangle "[[ Observation-observationMicroorgIdentAndSuscept.html 4-sepsis Observation\nMicroorganism\nidentification and susceptibility ]]" as OMIS <<$bProcess>><<resource>> #APPLICATION
rectangle "[[ Observation-ObservationEcoli.html Organism Identification: E.coli ]]" as OIE <<$bProcess>><<resource>> #APPLICATION
rectangle "[[ Observation-ObservationSusceptibilityEcoli.html Susceptibility\nE.coli ]]" as STE <<$bProcess>><<resource>> #APPLICATION
rectangle "[[ Observation-ObservationGramStainResultEcoli.html Gram Stain\nE.coli ]]" as GSE <<$bProcess>><<resource>> #APPLICATION
rectangle "[[ Observation-ObservationKpneumoniae.html Organism Identification: K.Pneumoniae ]]" as OIK <<$bProcess>><<resource>> #APPLICATION
rectangle "[[ Observation-ObservationSusceptibilityKpneumoniae.html Susceptibility\nK.Pneumoniae ]]" as STK <<$bProcess>><<resource>> #APPLICATION
rectangle "[[ Observation-ObservationGramStainResultKpneumoniae.html Gram Stain\nK.Pneumoniae ]]" as GSK <<$bProcess>><<resource>> #APPLICATION

SRG <-right-  DRG : [LAB-1]: basedOn
DRG -down-> OMA : [LAB-2]: result
DRG -down-> OMANA : [LAB-3]: result
OMA -up-> SRG : [LAB-4]: basedOn
OMA -down-> OMTE : [LAB-4]: triggeredBy
OMTE -up-> SRG : [LAB-5]: basedOn
OMA -down-> OMTK : [LAB-4]: triggeredBy
OMTK -up-> SRG : [LAB-5]: basedOn
OMA -down-> OMIS : [LAB-5]: triggeredBy
OMIS -down-> OIE : [LAB-6]: hasMember
OIE -down-> GSE : [LAB-7]: hasMember
OIE -down-> STE : [LAB-7]: hasMember
OMIS -down-> OIK : [LAB-6]: hasMember
OIK -down-> GSK : [LAB-7]: hasMember
OIK -down-> STK : [LAB-7]: hasMember

legend left
[Lab-1] based On→Diagnostic Reports requested by Sub-Service Request Growth
[Lab-2] result→Observation aerobic Growth POS, triggering further Observations
[Lab-3] result→Observation anarobe Growth NEG
[Lab-4] triggeredBy→Observations triggeredBy Observation aerobic Growth POS: 2 Observations with MALDI-TOF Method (E.coli, K.pneumoniae)-
[Lab-5] triggeredBy→Observations triggeredBy Observation aerobic Growth POS: Observation Microorganism and Susceptibility as Container for:-
[Lab-6] hasMember→2 Observations with Culture and Gram Stain Methods (E.coli, K.pneumoniae)
[Lab-7] hasMember→Each Organism idendified (E.coli, K.pneumoniae) contains an Observation of Susceptibility and Gram Stain
====
Note: To use the links in the Rectangles open image in a new tab
endlegend
@enduml