@startuml 4-sepsis-task

skinparam rectangle<<resource>> {
  roundCorner 12
  BackgroundColor Blue
  BorderColor Black
  ArrowColor Black
  FontName Arial
  FontSize 16
  FontStyle Bold
}

rectangle "[[ CarePlan-4-sepsis-CarePlan.html CarePlan\n4-sepsis-CarePlan ]] " as CP <<$bProcess>><<resource>> #Chartreuse
rectangle "[[ ServiceRequest-4-sepsis-ServiceRequest.html ServiceRequenst\n4-sepsis ServiceRequest]] " as SR <<$bProcess>><<resource>> #Yellow
rectangle "[[ ServiceRequest-4-sepsis-ServiceRequestCBCDiff.html ServiceRequenst\n4-sepsis ServiceRequest CBC Diff ]] " as SRDIFF <<$bProcess>><<resource>> #LightYellow
rectangle "[[ ServiceRequest-4-sepsis-ServiceRequestCRP.html ServiceRequenst\n4-sepsis ServiceRequest CRP ]] " as SRCRP <<$bProcess>><<resource>> #LightYellow
rectangle "[[ ServiceRequest-4-sepsis-ServiceRequestGrowth.html ServiceRequenst\n4-sepsis ServiceRequest Growth ]] " as SRG <<$bProcess>><<resource>> #LightYellow

rectangle "[[ DiagnosticReport-4-sepsis-DiagnosticReportGrowth.html DiagnosticReport\n4-sepsis DiagnosticReport Growth ]]" as DRG <<$bProcess>><<resource>> #LightSkyBlue
rectangle "[[ DiagnosticReport-4-sepsis-DiagnosticReportCBCDiff.html DiagnosticReport\n4-sepsis DiagnosticReport CBC Diff ]]" as DRDIFF <<$bProcess>><<resource>> #LightSkyBlue
rectangle "[[ DiagnosticReport-4-sepsis-DiagnosticReportCRP.html DiagnosticReport\n4-sepsis DiagnosticReport CRP ]]" as DRCRP <<$bProcess>><<resource>> #LightSkyBlue

rectangle "[[ Observation-observationMicrobiolGrowthAerobe.html 4-sepsis Observation\nMicrobiological Growth Aerobe: POS]]" as OMA <<$bProcess>><<resource>> #APPLICATION
rectangle "[[ Observation-observationMicrobiolGrowthAnaerobe.html 4-sepsis Observation\nMicrobiological Growth Anaerobe: NEG]]" as OMANA <<$bProcess>><<resource>> #APPLICATION

rectangle "[[ Task-4-sepsis-Task.html Sepsis Workup  Task\n4-sepsis-Task ]]" as T1 <<$bProcess>><<resource>> #LightGray
rectangle "[[ Specimen-4-sepsis-Blood-bactec-plus-aerobic.html Aerobic Blood Culture Specimen\n4-sepsis-Bactec Plus aerobic ]]" as BBSA <<$bProcess>><<resource>> #LightCoral
rectangle "[[ Specimen-4-sepsis-Blood-bactec-plus-anaerobic.html AnaerobicBlood Culture Specimen\n4-sepsis-Bactec Plus anaerobic ]]" as BBSANA <<$bProcess>><<resource>> #LightCoral
rectangle "[[ Specimen-4-sepsis-Blood.html Blood Specimen\n4-sepsis-Blood ]]" as BS <<$bProcess>><<resource>> #LightCoral
rectangle "[[ Specimen-4-sepsis-Serum.html Serum Specimen\n4-sepsis-Serum ]]" as SS <<$bProcess>><<resource>> #LightCoral

SR <-down- SRG : [LAB-3]: basedOn
SR <-down- SRDIFF : [LAB-3]: basedOn
SR <-down- SRCRP : [LAB-3]: basedOn
SRG <-down- DRG : [LAB-4]: basedOn
SRDIFF <-down- DRDIFF : [LAB-4]: basedOn
SRCRP <-down- DRCRP : [LAB-4]: basedOn
DRG -down-> OMA : [LAB-5]: result
DRG -down-> OMANA : [LAB-5]: result

SR <-up- T1 : [LAB-1]: focus
CP <-left- T1 : [LAB-0]: basedOn
T1 <-left- BBSA : [LAB-2]: input

BBSANA -down-> T1 : [LAB-2]: input
T1 <-left- BS : [LAB-2]: input
T1 <-left- SS : [LAB-2]: input

legend left
[Lab-0] based On → Task is based on 4-sepsis-CarePlan
[Lab-1] focus → Service Request is fullfilled by Task Sepsis Workup
[Lab-2] input → Specimen information used by Task Sepsis Workup
[Lab-3] based On → Sub-Service Requests grouped by 4-sepsis ServiceRequest
[Lab-4] based On → Diagnostic Reports requested by Sub-Service Requests
[Lab-5] result → Observations as Results of Diagnostic Report
====
Note: To use the links in the Rectangles open image in a new tab
endlegend

@enduml
