@startuml 4-sepsis-task

skinparam rectangle<<resource>> {
  roundCorner 12
  BackgroundColor Blue
  BorderColor Black
  ArrowColor Black
  FontName Arial
  FontSize 16
  FontStyle Bold
}

rectangle "[[ ServiceRequest-4-sepsis-ServiceRequest.html 4-sepsis ServiceRequest]] " as SR <<$bProcess>><<resource>> #Yellow
rectangle "[[ ServiceRequest-4-sepsis-ServiceRequestCBCDiff.html 4-sepsis ServiceRequest\nCBC Diff ]] " as SRDIFF <<$bProcess>><<resource>> #LightYellow
rectangle "[[ ServiceRequest-4-sepsis-ServiceRequestCRP.html 4-sepsis ServiceRequest\nCRP ]] " as SRCRP <<$bProcess>><<resource>> #LightYellow
rectangle "[[ ServiceRequest-4-sepsis-ServiceRequestGrowth.html 4-sepsis ServiceRequest\nGrowth ]] " as SRG <<$bProcess>><<resource>> #LightYellow

rectangle "[[ DiagnosticReport-4-sepsis-DiagnosticReportGrowth.html 4-sepsis DiagnosticReport\nGrowth ]]" as DRG <<$bProcess>><<resource>> #LightSkyBlue
rectangle "[[ DiagnosticReport-4-sepsis-DiagnosticReportCBCDiff.html 4-sepsis DiagnosticReport\nCBC Diff ]]" as DRDIFF <<$bProcess>><<resource>> #LightSkyBlue
rectangle "[[ DiagnosticReport-4-sepsis-DiagnosticReportCRP.html 4-sepsis DiagnosticReport\nCRP ]]" as DRCRP <<$bProcess>><<resource>> #LightSkyBlue

rectangle "[[ Observation-4-sepsis-ObservationMicrobiolGrowthAerobic.html 4-sepsis Observation\nMicrobiological Growth Aerobic: POS]]" as OMA <<$bProcess>><<resource>> #APPLICATION
rectangle "[[ Observation-ObservationMicrobiolGrowthAnaerobic.html 4-sepsis Observation\nMicrobiological Growth Anaerobic: NEG]]" as OMANA <<$bProcess>><<resource>> #APPLICATION

rectangle "[[ Task-SepsisWorkup.html 4-sepsis Task\nSepsis Workup]]" as T1 <<$bProcess>><<resource>> #LightGray
rectangle "[[ Specimen-4-sepsis-Blood-bactec-plus.html 4-sepsis Specimen\nBlood Bactec Plus ]]" as BBS <<$bProcess>><<resource>> #LightCoral
rectangle "[[ Specimen-Blood-4-sepsis.html 4-sepsis Specimen\nBlood ]]" as BS <<$bProcess>><<resource>> #LightCoral
rectangle "[[ Specimen-Serum-4-sepsis.html 4-sepsis Specimen\nSerum ]]" as SS <<$bProcess>><<resource>> #LightCoral

SR <-down- SRG : [LAB-3]: basedOn
SR <-down- SRDIFF : [LAB-3]: basedOn
SR <-down- SRCRP : [LAB-3]: basedOn
SRG <-down- DRG : [LAB-4]: basedOn
SRDIFF <-down- DRDIFF : [LAB-4]: basedOn
SRCRP <-down- DRCRP : [LAB-4]: basedOn
DRG -down-> OMA : [LAB-5]: result
DRG -down-> OMANA : [LAB-5]: result

SR <-up- T1 : [LAB-1]: basedOn
T1 <-left- BBS : [LAB-2]: input
T1 <-left- BS : [LAB-2]: input
T1 <-left- SS : [LAB-2]: input

legend left
[Lab-1] based On → Service Request is fullfilled by Task Sepsis Workup
[Lab-2] input → Specimen information used by Task Sepsis Workup
[Lab-3] based On → Sub-Service Requests grouped by 4-sepsis ServiceRequest
[Lab-4] based On → Diagnostic Reports requested by Sub-Service Requests
[Lab-5] result → Observations as Results of Diagnostic Report
====
Note: To use the links in the Rectangles open image in a new tab
endlegend

@enduml
