@startuml LabOrder Workflow Diagram

-> "OrderPlacer\n Computer-based Patient-Record-System"
  --> if "successful?" then

  -->[true] "process tests"

  if "all tests verified" then
    ->[true] "final Report" as a3
  else
    if "Other tests successful" then
      -left-> "partial Report"
    else
      -->[false] "send partial test"
    endif
  endif

else

  ->[false] "order cancelled"

endif

a3 --> if "last test" then
  --> "action 7"
else
  -> "action 8"
endif

@enduml
