@startuml RenalInsufficiencyPanel

skinparam rectangle<<resource>> {
  roundCorner 12
  BackgroundColor Blue
  BorderColor Black
  ArrowColor Black
  FontName Arial
  FontSize 16
  FontStyle Bold
}

rectangle "[[ ServiceRequest-panel-renal-insufficiency-order.html SR Renal Insufficiency Panel ]] " as RIP <<$bProcess>><<resource>> #Yellow
rectangle "[[ ServiceRequest-lab-order-eGFR.html SR eGFR CKD-EPI 2021 ]] " as EGFR <<$bProcess>><<resource>> #LightYellow
rectangle "[[ ServiceRequest-lab-order-uACR.html SR Albumin/Creatinine Ratio in Urine ]] " as UACR <<$bProcess>><<resource>> #LightYellow
rectangle "[[ ServiceRequest-lab-order-urine-albumin.html SR Albumin in Urine ]] " as UA <<$bProcess>><<resource>> #LightYellow
rectangle "[[ ServiceRequest-lab-order-urine-creatinine.html SR Creatinine in Urine ]] " as UC <<$bProcess>><<resource>> #LightYellow

rectangle "[[ PlanDefinition-LabServiceRenalInsufficiency.html PlanDefinition\nRenal Insufficiency Service \n type panel ]]" as RIS <<$bProcess>><<resource>> #LightGray

rectangle "[[ ActivityDefinition-procedure-lab-panel-renal-insufficiency.html ActivityDefinition\nProcedure Renal Insufficiency ]]" as PRI <<$bProcess>><<resource>> #MediumTurquoise

rectangle "[[ ActivityDefinition-procedure-lab-eGFR-ckd-epi.html ActivityDefinition\nProcedure eGFK CKD-EPI ]]" as PGFK <<$bProcess>><<resource>> #MediumTurquoise
rectangle "[[ ActivityDefinition-procedure-urine-uACR.html ActivityDefinition\nProcedure uACR ]]" as PACR <<$bProcess>><<resource>> #MediumTurquoise

RIP <-down- EGFR : [LAB-3]: basedOn
RIP <-down- UACR : [LAB-3]: basedOn
UACR <-down- UA : [LAB-3]: basedOn
UACR <-down- UC : [LAB-4]: basedOn

RIS <-down- RIP : [LAB-1]: instanciatesCanonical
RIS <-up- PRI : [LAB-1]: definitionCanonical

RIS <-right- PACR : [LAB-2]: \naction.definitionCanonical
RIS <-left- PGFK : [LAB-2]: \naction.definitionCanonical

@enduml
