@startuml observation
title SequenceDiagram as example
hide footbox
participant "1st actor" as DocumentSource
participant "2nd actor" as DocumentRecipient
autonumber
activate DocumentSource
activate DocumentRecipient
DocumentSource -> DocumentRecipient : Request to provide DocumentReference with embedded Document 
DocumentRecipient -> DocumentRecipient : Extract the document
DocumentRecipient -> DocumentRecipient : Validate document 
DocumentRecipient -> DocumentRecipient : Queue document for processing 
DocumentRecipient --> DocumentSource : Document accepted and queued for processing 
DocumentSource -> DocumentRecipient : Check if document has been processed 
DocumentRecipient --> DocumentSource : DocumentReference either completed, failed or in-progress 
deactivate DocumentSource
deactivate DocumentRecipient
@enduml