@startuml test

class MyClass {
  int count
  --
  int publicNumber
  .. [Strings] ..
  String name
  --
  methodOne()
  methodTwo()
}

class YourClass {
  -int privateCount 
  #int publicNumber 
  .. [Strings] ..
  +String name
  --
  ~methodPackageProtected()
  methodTwo()
}

class SecondClass {
  int aSecretField
  void secretMethod()
}
note left : this class is\na secretClass

MyClass <-- SecondClass
MyClass <--right-- ThirdClass

@enduml