Instance: single-test-serum-capillary-fasting
InstanceOf: SpecimenDefinition
Title: "SpecimenDefinition Serum Capillary Blood, 12 h fasting"
Description: "Serum Capillary Blood, 12 h fasting, for single test"
Usage: #example
* typeCollected = $sct#122554006 "Capillary blood specimen"
* patientPreparation[0].text = "12 hour fasting"
* patientPreparation[+] = $sct#263678003 "At rest"
* timeAspect = "preferrably morning time"
* typeTested[0].type = $sct#122554006 "Capillary blood specimen"
* typeTested[=].preference = #preferred
* typeTested[=].container.material = $sct#61088005 "plastic"
* typeTested[=].container.type = $sct#767384004 "Evacuated blood collection tube with clot activator"
* typeTested[=].container.cap = http://terminology.hl7.org/CodeSystem/container-cap#red
* typeTested[=].container.cap.text = "red cap"
* typeTested[=].container.description = "red cap plastic tube 2 mL"
* typeTested[=].container.capacity = 2 'mL' "milliliter"
* typeTested[=].container.minimumVolumeQuantity = 0.5 'mL' "milliliter"
* typeTested[=].handling[0].temperatureQualifier.text = "Ambient temperature"
* typeTested[=].handling[=].temperatureRange.low = 15 'Cel' "°C"
* typeTested[=].handling[=].temperatureRange.high = 25 'Cel' "°C"
* typeTested[=].handling[=].maxDuration = 60 'min' "minute"
* typeTested[=].handling[+].temperatureQualifier.text = "Refrigerated temperature"
* typeTested[=].handling[=].temperatureRange.low = 2 'Cel' "°C"
* typeTested[=].handling[=].temperatureRange.high = 8 'Cel' "°C"
* typeTested[=].handling[=].maxDuration = 8 'h' "hour"
* typeTested[+].type = $sct#119361006 "Plasma specimen"
* typeTested[=].preference = #alternate
* typeTested[=].container.material = $sct#32039001 "glass"
* typeTested[=].container.type = $sct#767390000 "Evacuated blood collection tube with heparin lithium and gel separator"
* typeTested[=].container.cap = $container-cap#green "green cap"
* typeTested[=].container.minimumVolumeQuantity = 2 'mL' "ml"
* typeTested[=].rejectionCriterion[0] = $rejection-criteria#insufficient "insufficient specimen volume"
* typeTested[=].rejectionCriterion[+] = $rejection-criteria#hemolized "hemolized specimen"
* typeTested[=].handling[0].temperatureQualifier.text = "Ambient temperature"
* typeTested[=].handling[=].temperatureRange.low = 15 'Cel' "°C"
* typeTested[=].handling[=].temperatureRange.high = 25 'Cel' "°C"
* typeTested[=].handling[=].maxDuration = 60 'min' "minute"
* typeTested[=].handling[+].temperatureQualifier.text = "Refrigerated temperature"
* typeTested[=].handling[=].temperatureRange.low = 2 'Cel' "°C"
* typeTested[=].handling[=].temperatureRange.high = 8 'Cel' "°C"
* typeTested[=].handling[=].maxDuration = 8 'h' "hour"