@host = http://test.fhir.ch/r4

###
PUT {{host}}/Patient/MonikaWegmueller HTTP/1.1
Content-Type: application/fhir+xml

< ./patient/MonikaWegmueller.xml

###
PUT {{host}}/Patient/MonikaWegmuellerRecipient HTTP/1.1
Content-Type: application/fhir+xml

< ./patient/MonikaWegmuellerRecipient.xml

###
PUT {{host}}/Practitioner/FamilienHausarzt HTTP/1.1
Content-Type: application/fhir+xml

< ./practitioner/FamilienHausarzt.xml

###
PUT {{host}}/Organization/Hausarzt HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/Hausarzt.xml



###
PUT {{host}}/MedicationRequest/MedReqNorvasc HTTP/1.1
Content-Type: application/fhir+xml

< ./medicationrequest/MedReqNorvasc.xml

###
PUT {{host}}/MedicationDispense/MedDispBeloczok HTTP/1.1
Content-Type: application/fhir+xml

< ./medicationdispense/MedDispBeloczok.xml

###
PUT {{host}}/MedicationStatement/MedStatBeloczok HTTP/1.1
Content-Type: application/fhir+xml

< ./medicationstatement/MedStatBeloczok.xml

###
PUT {{host}}/MedicationStatement/MedStatNorvasc HTTP/1.1
Content-Type: application/fhir+xml

< ./medicationstatement/MedStatNorvasc.xml

###
PUT {{host}}/MedicationStatement/MedStatTriatec HTTP/1.1
Content-Type: application/fhir+xml

< ./medicationstatement/MedStatTriatec.xml

###
PUT {{host}}/Observation/PharmaceuticalAdvice HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/PharmaceuticalAdvice.xml



###
PUT {{host}}/DocumentReference/DocRef-1-1-MedicationTreatmentPlan HTTP/1.1
Content-Type: application/fhir+xml

< ./documentreference/DocRef-1-1-MedicationTreatmentPlan.xml

###
PUT {{host}}/DocumentReference/DocRef-1-2-MedicationDispense HTTP/1.1
Content-Type: application/fhir+xml

< ./documentreference/DocRef-1-2-MedicationDispense.xml

###
PUT {{host}}/DocumentReference/DocRef-2-1-MedicationList HTTP/1.1
Content-Type: application/fhir+xml

< ./documentreference/DocRef-2-1-MedicationList.xml

###
PUT {{host}}/DocumentReference/DocRef-2-2-PharmaceuticalAdvice HTTP/1.1
Content-Type: application/fhir+xml

< ./documentreference/DocRef-2-2-PharmaceuticalAdvice.xml

###
PUT {{host}}/DocumentReference/DocRef-2-3-MedicationTreatmentPlan HTTP/1.1
Content-Type: application/fhir+xml

< ./documentreference/DocRef-2-3-MedicationTreatmentPlan.xml

###
PUT {{host}}/DocumentReference/DocRef-2-7-MedicationCard HTTP/1.1
Content-Type: application/fhir+xml

< ./documentreference/DocRef-2-7-MedicationCard.xml



###
PUT {{host}}/Composition/1-1-MedicationTreatmentPlan HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/1-1-MedicationTreatmentPlan.xml

###
PUT {{host}}/Composition/2-1-MedicationList HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/2-1-MedicationList.xml

###
PUT {{host}}/Composition/2-2-PharmaceuticalAdvice HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/2-2-PharmaceuticalAdvice.xml

###
PUT {{host}}/Composition/2-6-MedicationPrescription HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/2-6-MedicationPrescription.xml

###
PUT {{host}}/Composition/2-4-MedicationDispense HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/2-4-MedicationDispense.xml

###
PUT {{host}}/Composition/2-7-MedicationCard HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/2-7-MedicationCard.xml






###
GET {{host}}/Patient/MonikaWegmueller HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Patient/MonikaWegmuellerRecipient HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Organization/Hausarzt HTTP/1.1
Content-Type: application/fhir+xml


###
GET {{host}}/Composition/1-1-MedicationTreatmentPlan/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/2-1-MedicationList/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/2-2-PharmaceuticalAdvice/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/2-6-MedicationPrescription/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/2-4-MedicationDispense/$document HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/2-7-MedicationCard/$document HTTP/1.1
Content-Type: application/fhir+xml


###
GET {{host}}/DocumentReference/DocRef-1-1-MedicationTreatmentPlan HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Patient?name:family=Wegmüller HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Patient?_id=MonikaWegmueller HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/DocumentReference?_identifier:MR=11111111 HTTP/1.1
Content-Type: application/fhir+xml


###
GET {{host}}/DocumentReference?patient.identifier=urn:oid:2.999|11111111 HTTP/1.1
Content-Type: application/fhir+xml